// Generated by scripts/generate_precision_tiers.py — do not edit by hand.

/// Measured benchmark precision tier for a built-in rule (advisory only).
pub fn precision_tier(rule_id: &str) -> Option<&'static str> {
    match rule_id {
        "SQLCOST001" => Some("verified-high"),
        "SQLCOST002" => Some("verified-high"),
        "SQLCOST003" => Some("verified-high"),
        "SQLCOST004" => Some("verified-high"),
        "SQLCOST005" => Some("verified-high"),
        "SQLCOST006" => Some("verified-medium"),
        "SQLCOST007" => Some("verified-high"),
        "SQLCOST008" => Some("verified-high"),
        "SQLCOST009" => Some("informational"),
        "SQLCOST010" => Some("informational"),
        "SQLCOST011" => Some("informational"),
        "SQLCOST012" => Some("verified-medium"),
        "SQLCOST013" => Some("verified-high"),
        "SQLCOST014" => Some("verified-high"),
        "SQLCOST015" => Some("verified-high"),
        "SQLCOST016" => Some("informational"),
        "SQLCOST017" => Some("verified-low"),
        "SQLCOST018" => Some("verified-high"),
        "SQLCOST019" => Some("verified-high"),
        "SQLCOST020" => Some("verified-high"),
        "SQLCOST021" => Some("informational"),
        "SQLCOST022" => Some("informational"),
        "SQLCOST023" => Some("informational"),
        "SQLCOST024" => Some("informational"),
        "SQLCOST025" => Some("informational"),
        "SQLCOST026" => Some("informational"),
        "SQLCOST027" => Some("informational"),
        "SQLCOST028" => Some("verified-high"),
        "SQLCOST029" => Some("verified-high"),
        "SQLCOST030" => Some("verified-high"),
        "SQLCOST031" => Some("verified-high"),
        "SQLCOST032" => Some("informational"),
        "SQLCOST033" => Some("verified-high"),
        "SQLCOST034" => Some("informational"),
        "SQLCOST035" => Some("verified-high"),
        "SQLCOST036" => Some("verified-high"),
        "SQLCOST037" => Some("verified-high"),
        "SQLCOST038" => Some("verified-high"),
        "SQLCOST039" => Some("verified-high"),
        "SQLCOST040" => Some("verified-high"),
        "SQLCOST041" => Some("verified-high"),
        "SQLCOST042" => Some("verified-high"),
        "SQLCOST043" => Some("informational"),
        "SQLCOST044" => Some("verified-high"),
        "SQLCOST045" => Some("informational"),
        "SQLCOST046" => Some("informational"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::precision_tier;

    #[test]
    fn every_builtin_rule_has_tier() {
        for rule_id in crate::BUILTIN_RULE_IDS {
            assert!(precision_tier(rule_id).is_some(), "{rule_id} missing tier");
        }
    }
}
