#!/usr/bin/env python3
"""Generate committed precision tier tables from rule_tp_evidence.json."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "tests" / "benchmarks" / "rule_tp_evidence.json"
TOML_OUT = ROOT / "tests" / "benchmarks" / "precision_tiers.toml"
RUST_OUT = ROOT / "crates" / "costguard-protocol" / "src" / "precision_tiers.rs"

INFRASTRUCTURE_RULES = {
    "SQLCOST023",
    "SQLCOST024",
    "SQLCOST025",
    "SQLCOST026",
    "SQLCOST027",
    "SQLCOST045",
    "SQLCOST046",
    "SQLCOST047",
}


def fetch_rule_ids() -> list[str]:
    from costguard_tooling import costguard_binary

    proc = subprocess.run(
        [str(costguard_binary()), "rules", "--format", "json"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(proc.stderr.strip() or "costguard rules failed")
    return sorted(rule["id"] for rule in json.loads(proc.stdout))


def tier_for_rule(rule_id: str, evidence: dict) -> tuple[str, str]:
    if rule_id in INFRASTRUCTURE_RULES:
        return "informational", "infrastructure or metadata rule"
    entry = evidence.get(rule_id)
    if not entry:
        return "unverified", "missing benchmark evidence"
    if not entry.get("pass"):
        return "unverified", "benchmark census did not pass"
    examined = int(entry.get("examined") or 0)
    tp = int(entry.get("tp") or 0)
    if examined == 0:
        return "informational", entry.get("pass_reason", "no sampled findings")
    precision = tp / examined
    if precision >= 0.9:
        return "verified-high", f"{tp}/{examined} sampled TP ({precision:.0%})"
    if precision >= 0.7:
        return "verified-medium", f"{tp}/{examined} sampled TP ({precision:.0%})"
    return "verified-low", f"{tp}/{examined} sampled TP ({precision:.0%})"


def render_toml(tiers: dict[str, dict[str, str]], rule_ids: list[str]) -> str:
    lines = [
        "# Generated by scripts/generate_precision_tiers.py — do not edit by hand.",
        "",
    ]
    for rule_id in rule_ids:
        entry = tiers[rule_id]
        lines.append("[[rule]]")
        lines.append(f'id = "{rule_id}"')
        lines.append(f'tier = "{entry["tier"]}"')
        lines.append(f'notes = "{entry["notes"]}"')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_rust(tiers: dict[str, dict[str, str]], rule_ids: list[str]) -> str:
    arms = "\n".join(
        f'        "{rule_id}" => Some("{tiers[rule_id]["tier"]}"),'
        for rule_id in rule_ids
    )
    return f"""// Generated by scripts/generate_precision_tiers.py — do not edit by hand.

/// Measured benchmark precision tier for a built-in rule (advisory only).
pub fn precision_tier(rule_id: &str) -> Option<&'static str> {{
    match rule_id {{
{arms}
        _ => None,
    }}
}}

#[cfg(test)]
mod tests {{
    use super::precision_tier;

    #[test]
    fn every_builtin_rule_has_tier() {{
        for rule_id in crate::BUILTIN_RULE_IDS {{
            assert!(precision_tier(rule_id).is_some(), "{{rule_id}} missing tier");
        }}
    }}
}}
"""


def build_tiers(evidence: dict, rule_ids: list[str]) -> dict[str, dict[str, str]]:
    orphaned = sorted(INFRASTRUCTURE_RULES.difference(rule_ids))
    if orphaned:
        raise ValueError(
            "infrastructure rules missing from registry: " + ", ".join(orphaned)
        )
    return {
        rule_id: dict(zip(["tier", "notes"], tier_for_rule(rule_id, evidence), strict=True))
        for rule_id in rule_ids
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 when generated tier files are stale",
    )
    args = parser.parse_args()

    if not EVIDENCE.exists():
        print(f"missing evidence: {EVIDENCE}", file=sys.stderr)
        return 1

    evidence = json.loads(EVIDENCE.read_text(encoding="utf-8"))
    rule_ids = fetch_rule_ids()
    try:
        tiers = build_tiers(evidence, rule_ids)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    toml_text = render_toml(tiers, rule_ids)
    rust_text = render_rust(tiers, rule_ids)

    if args.check:
        stale = False
        for path, expected in ((TOML_OUT, toml_text), (RUST_OUT, rust_text)):
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                print(f"stale precision tiers: {path}", file=sys.stderr)
                stale = True
        return 1 if stale else 0

    TOML_OUT.write_text(toml_text, encoding="utf-8")
    RUST_OUT.write_text(rust_text, encoding="utf-8")
    print(f"wrote {TOML_OUT}")
    print(f"wrote {RUST_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
