#!/usr/bin/env python3
"""Regenerate or offline-verify hashed Python dependency locks."""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON_FLOOR = "3.11"
LOCK_PAIRS = (
    (ROOT / "requirements-eval.txt", ROOT / "requirements-eval.lock"),
    (ROOT / "requirements-judge.txt", ROOT / "requirements-judge.lock"),
)


def source_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def lock_header(source: Path) -> str:
    return "\n".join(
        (
            "# Generated by scripts/lock_python_deps.py; do not edit.",
            f"# source: {source.name}",
            f"# source-sha256: {source_sha256(source)}",
            f"# python-floor: {PYTHON_FLOOR}",
            "# resolver: uv pip compile --universal --generate-hashes",
            "",
        )
    )


def validate_lock(source: Path, lock: Path) -> None:
    if not lock.is_file():
        raise ValueError(f"missing lock file: {lock}")
    text = lock.read_text(encoding="utf-8")
    expected = lock_header(source)
    if not text.startswith(expected):
        raise ValueError(
            f"malformed or stale metadata in {lock.name}; regenerate with scripts/lock_python_deps.py"
        )
    body = text[len(expected) :]
    if not body.strip() or "--hash=sha256:" not in body:
        raise ValueError(f"{lock.name} does not contain hashed requirements")


def compile_lock(uv: str, source: Path, lock: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="costguard-lock-") as temporary:
        resolved = Path(temporary) / lock.name
        subprocess.run(
            [
                uv,
                "pip",
                "compile",
                "--universal",
                "--generate-hashes",
                "--python-version",
                PYTHON_FLOOR,
                "--no-header",
                "--output-file",
                str(resolved),
                str(source),
            ],
            cwd=ROOT,
            check=True,
        )
        text = lock_header(source) + resolved.read_text(encoding="utf-8")
        lock.write_text(text, encoding="utf-8")
    validate_lock(source, lock)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify lock metadata and input hashes without uv or network access",
    )
    args = parser.parse_args()

    if args.check:
        failed = False
        for source, lock in LOCK_PAIRS:
            try:
                validate_lock(source, lock)
            except (OSError, ValueError) as error:
                print(f"error: {error}", file=sys.stderr)
                failed = True
        return 1 if failed else 0

    uv = shutil.which("uv")
    if uv is None:
        print("error: uv is required to regenerate Python locks", file=sys.stderr)
        return 2
    for source, lock in LOCK_PAIRS:
        compile_lock(uv, source, lock)
        print(f"wrote {lock}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
