//! Scaffold Costguard into a dbt project (workflow + optional config).

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Default)]
pub struct InitOptions {
    pub warehouse: Option<String>,
    pub force: bool,
    pub no_workflow: bool,
    pub no_config: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct InitOutcome {
    pub created: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
    pub warehouse: String,
}

/// ponytail: profiles.yml is often gitignored; detection is best-effort only.
pub fn detect_warehouse(root: &Path) -> String {
    let profile = read_dbt_profile_name(root);
    if let Some(profile_name) = profile {
        if let Some(adapter) = read_profiles_adapter(root, &profile_name) {
            if let Some(warehouse) = map_adapter_to_warehouse(&adapter) {
                return warehouse;
            }
        }
    }
    "generic".to_string()
}

pub fn init_project(root: &Path, opts: &InitOptions) -> Result<InitOutcome> {
    let warehouse = opts
        .warehouse
        .clone()
        .unwrap_or_else(|| detect_warehouse(root));
    let version = env!("CARGO_PKG_VERSION");
    let mut outcome = InitOutcome {
        warehouse: warehouse.clone(),
        ..InitOutcome::default()
    };

    if !opts.no_workflow {
        let workflow_path = root.join(".github/workflows/costguard.yml");
        write_if_allowed(
            &workflow_path,
            &workflow_template(&warehouse, version),
            opts.force,
            &mut outcome,
        )?;
    }

    if !opts.no_config {
        let config_path = root.join("costguard.toml");
        write_if_allowed(
            &config_path,
            &config_template(&warehouse),
            opts.force,
            &mut outcome,
        )?;
    }

    Ok(outcome)
}

fn write_if_allowed(
    path: &Path,
    contents: &str,
    force: bool,
    outcome: &mut InitOutcome,
) -> Result<()> {
    if path.exists() && !force {
        outcome.skipped.push(path.to_path_buf());
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    std::fs::write(path, contents)
        .with_context(|| format!("failed to write {}", path.display()))?;
    outcome.created.push(path.to_path_buf());
    Ok(())
}

fn read_dbt_profile_name(root: &Path) -> Option<String> {
    let path = root.join("dbt_project.yml");
    let text = std::fs::read_to_string(&path).ok()?;
    let value: serde_yaml::Value = serde_yaml::from_str(&text).ok()?;
    value
        .get("profile")
        .and_then(|v| v.as_str())
        .map(str::to_string)
}

fn read_profiles_adapter(root: &Path, profile_name: &str) -> Option<String> {
    for profiles_path in [root.join("profiles.yml"), home_dbt_profiles()] {
        if let Some(adapter) = read_adapter_from_profiles(&profiles_path, profile_name) {
            return Some(adapter);
        }
    }
    None
}

fn home_dbt_profiles() -> PathBuf {
    dirs_or_home().join(".dbt/profiles.yml")
}

fn dirs_or_home() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn read_adapter_from_profiles(path: &Path, profile_name: &str) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    let value: serde_yaml::Value = serde_yaml::from_str(&text).ok()?;
    let profile = value.get(profile_name)?;
    let outputs = profile.get("outputs")?.as_mapping()?;
    let target = profile
        .get("target")
        .and_then(|v| v.as_str())
        .or_else(|| outputs.keys().next()?.as_str())?;
    outputs
        .get(target)
        .and_then(|output| output.get("type"))
        .and_then(|v| v.as_str())
        .map(str::to_string)
}

pub fn map_adapter_to_warehouse(adapter: &str) -> Option<String> {
    match adapter.to_ascii_lowercase().as_str() {
        "snowflake" => Some("snowflake".into()),
        "bigquery" => Some("bigquery".into()),
        "databricks" => Some("databricks".into()),
        "redshift" => Some("redshift".into()),
        "postgres" => Some("postgres".into()),
        "duckdb" => Some("duckdb".into()),
        "trino" => Some("trino".into()),
        _ => None,
    }
}

fn workflow_template(warehouse: &str, version: &str) -> String {
    let version_tag = format!("v{version}");
    format!(
        r#"# Generated by costguard init. Commit this workflow to enable PR cost checks.
name: Costguard

on:
  pull_request:

jobs:
  costguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Uncomment and adjust when your CI already has dbt + credentials:
      # - run: dbt deps
      # - run: dbt compile --target dev

      - uses: hypertrial/costguard/.github/actions/costguard@v{version_tag}
        with:
          base: origin/${{{{ github.event.pull_request.base.ref }}}}
          warehouse: {warehouse}
          fail-on: high
          min-confidence: high
          block-only-new: true
          # fail-on-pr-cost-increase: "500" # requires priced [cost] configuration
"#
    )
}

fn config_template(warehouse: &str) -> String {
    format!(
        r#"# Generated by costguard init. See https://github.com/hypertrial/costguard/blob/main/docs/book/reference/configuration.md
warehouse = "{warehouse}"

# [scan]
# paths = ["models"]
# ignore = ["target", "dbt_packages"]

# [output]
# fail_on = "high"
# min_confidence = "high"
# min_confidence_filter = true

[gate]
block_only_new = true
# fail_on_pr_cost_increase = 500
# Requires enabled [cost] and [cost.pricing].model = "scan" or "compute".

# [dbt]
# manifest_path = "target/manifest.json"
# max_manifest_bytes = 536870912
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn maps_known_adapters() {
        assert_eq!(
            map_adapter_to_warehouse("snowflake").as_deref(),
            Some("snowflake")
        );
        assert_eq!(
            map_adapter_to_warehouse("BigQuery").as_deref(),
            Some("bigquery")
        );
        assert_eq!(map_adapter_to_warehouse("unknown"), None);
    }

    #[test]
    fn init_writes_and_skips_without_force() {
        let temp = tempdir().unwrap();
        fs::write(
            temp.path().join("dbt_project.yml"),
            "name: demo\nprofile: dev\n",
        )
        .unwrap();
        fs::write(
            temp.path().join("profiles.yml"),
            r#"
dev:
  target: prod
  outputs:
    prod:
      type: snowflake
"#,
        )
        .unwrap();

        let first = init_project(
            temp.path(),
            &InitOptions {
                force: false,
                ..InitOptions::default()
            },
        )
        .unwrap();
        assert_eq!(first.warehouse, "snowflake");
        assert_eq!(first.created.len(), 2);
        assert!(first.skipped.is_empty());

        let second = init_project(
            temp.path(),
            &InitOptions {
                force: false,
                ..InitOptions::default()
            },
        )
        .unwrap();
        assert!(second.created.is_empty());
        assert_eq!(second.skipped.len(), 2);
    }

    #[test]
    fn init_respects_warehouse_override() {
        let temp = tempdir().unwrap();
        let outcome = init_project(
            temp.path(),
            &InitOptions {
                warehouse: Some("trino".into()),
                ..InitOptions::default()
            },
        )
        .unwrap();
        assert_eq!(outcome.warehouse, "trino");
        let workflow =
            fs::read_to_string(temp.path().join(".github/workflows/costguard.yml")).unwrap();
        assert!(workflow.contains("warehouse: trino"));
        assert!(workflow.contains("@v"));
    }
}
